before_script:
    - date
    - uname -p
    - uname -s
    - printenv | sort

python:
    image: gpdowning/python
    script:
    - cat Makefile
    - make versions
    - ls -al
    - make test
    - ls -al
    - make ../cs373-collatz-tests
    - ls -al ../cs373-collatz-tests/
    - ls -al
    - make run
    - ls -al
    - make check
    - ls -al
