# stages:
#  - deploy
#  - test

# backend-deploy:
#   stage: deploy
#   script:
#    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
#    - eval "$(ssh-agent -s)"
#    - cat "$SSH_PRIVATE_KEY" | ssh-add -
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#    - ssh-keyscan -H $BACKEND_SERVER_IP >> ~/.ssh/known_hosts
#    - chmod 644 ~/.ssh/known_hosts
#    - scp -r ./backend $BACKEND_SERVER_IP:/home/ubuntu/stormshelters/backend
#    - cat ./remote.sh | ssh $BACKEND_SERVER_IP "bash -"
#   only:
#    - dev

# postman_tests:
#   stage: test
#   image:
#     name: postman/newman_alpine33
#     entrypoint: [""]
#   script:
#     - cd backend
#     - newman --version
#     - newman run postman_tests.json
#   needs:
#       - backend-deploy


cache:
  paths:
    - node_modules

stages:
  - build
  - test

frontend-build:
  stage: build
  image: node:18.18.0
  script:
    - cd frontend
    - npm install
    - CI=false npm run build

backend-build:
  stage: build
  image: python:3.10
  script:
    - cd backend
    - pip3 install -r requirements.txt

python-tests:
  image: python:3
  stage: test
  script:
    - cd backend
    - python tests.py
  # needs:
  #     - backend-deploy

# selenium-tests:
#   image: joyzoursky/python-chromedriver:3.9-selenium
#   stage: test
#   before_script:
#     - pip install -r frontend/requirements.txt
#   script:
#     - python frontend/guitests.py
