stages:
 - deploy
 - test

backend-deploy:
  stage: deploy
  script:
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - eval "$(ssh-agent -s)"
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - ssh-keyscan -H $BACKEND_SERVER_IP >> ~/.ssh/known_hosts
   - scp -r ./backend $BACKEND_SERVER_IP:/home/ubuntu/stormshelters/backend
   - cat ./remote.sh | ssh $BACKEND_SERVER_IP "bash -"
  only:
   - dev

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - cd backend
    - newman --version
    - newman run postman_tests.json
  needs:
      - backend-deploy

python-tests:
  image: python:3
  stage: test
  script:
    - cd backend
    - python tests.py
  needs:
      - backend-deploy