stages:
 - deploy
 - test

deploy:
  stage: deploy
  script:
   - mkdir -p ~/.ssh
   - echo "$SSH_PRIVATE_KEY" | > ~/.ssh/id_rsa
   - echo "$SSH_PRIVATE_KEY"
   - chmod 700 ~/.ssh
   - chmod 600 ~/.ssh/id_rsa
   - eval "$(ssh-agent -s)"
   - ssh-add ~/.ssh/id_rsa
   - ssh-keyscan -H $BACKEND_SERVER_IP >> ~/.ssh/known_hosts
   - scp -r ./backend $BACKEND_SERVER_IP:/home/ubuntu/stormshelters/backend
   - cat ./remote.sh | ssh $BACKEND_SERVER_IP "bash -"
  only:
   - dev

postman_tests:
  stage: test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - cd backend
    - newman --version
    - newman run postman_tests.json

python-tests:
  image: python:3
  stage: test
  script:
    - cd backend
    - python tests.py
