services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: idb-backend
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: idb-frontend
    ports:
      - "3000:3000"
    command: npm start